// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7FDaXsXCBKg_MXXc1LSudky4z4bKnZXc',
    appId: '1:752736817270:web:87703f0065c85e1084cf57',
    messagingSenderId: '752736817270',
    projectId: 'meal-7562f',
    authDomain: 'meal-7562f.firebaseapp.com',
    storageBucket: 'meal-7562f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ49NQlUemvXyiI3aomEaZ4SMqAw8X6xM',
    appId: '1:752736817270:android:9ca66e13889c9edd84cf57',
    messagingSenderId: '752736817270',
    projectId: 'meal-7562f',
    storageBucket: 'meal-7562f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBoqBi7pl-TBHPSn2jAuXqBqmuXZ1HYP8',
    appId: '1:752736817270:ios:9aa3d5465ba5390384cf57',
    messagingSenderId: '752736817270',
    projectId: 'meal-7562f',
    storageBucket: 'meal-7562f.firebasestorage.app',
    iosBundleId: 'com.example.meal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBoqBi7pl-TBHPSn2jAuXqBqmuXZ1HYP8',
    appId: '1:752736817270:ios:9aa3d5465ba5390384cf57',
    messagingSenderId: '752736817270',
    projectId: 'meal-7562f',
    storageBucket: 'meal-7562f.firebasestorage.app',
    iosBundleId: 'com.example.meal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7FDaXsXCBKg_MXXc1LSudky4z4bKnZXc',
    appId: '1:752736817270:web:768b63f6a4acce7984cf57',
    messagingSenderId: '752736817270',
    projectId: 'meal-7562f',
    authDomain: 'meal-7562f.firebaseapp.com',
    storageBucket: 'meal-7562f.firebasestorage.app',
  );
}
